// Centralized Google Gemini AI Service for Mr. Doc
const { GoogleGenerativeAI } = require('@google/generative-ai');
const { SYSTEM_CHAT_PROMPT, SYSTEM_SYMPTOM_CHECKER_PROMPT } = require('../utils/aiPrompts');

const getApiKey = () => process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || null;

// Supported Gemini Models fallback list for maximum API version compatibility
const CANDIDATE_MODELS = [
  'gemini-3.6-flash',
  'gemini-3.5-flash',
  'gemini-flash-latest',
  'gemini-2.5-flash-lite',
  'gemini-pro-latest',
  'gemini-1.5-flash'
];

/**
 * Generate Content trying candidate models sequentially until one succeeds
 */
const generateWithCandidateModels = async (prompt) => {
  const apiKey = getApiKey();
  if (!apiKey) return null;
  const genAI = new GoogleGenerativeAI(apiKey);

  let lastError = null;
  for (const modelName of CANDIDATE_MODELS) {
    try {
      const model = genAI.getGenerativeModel({ model: modelName });
      const result = await model.generateContent(prompt);
      const text = result.response.text();
      if (text && text.trim()) {
        return { text: text.trim(), modelUsed: modelName };
      }
    } catch (err) {
      lastError = err;
      // If error is invalid key, don't keep looping models
      if (err.message && err.message.includes('API_KEY_INVALID')) {
        throw err;
      }
    }
  }
  throw lastError || new Error('All candidate Gemini models failed');
};

/**
 * Generate AI Chat Response
 */
const generateChatResponse = async (message, history = []) => {
  const apiKey = getApiKey();

  if (apiKey) {
    try {
      const fullPrompt = `${SYSTEM_CHAT_PROMPT}\n\nUser Query: "${message}"`;
      const aiResult = await generateWithCandidateModels(fullPrompt);

      if (aiResult && aiResult.text) {
        let reply = aiResult.text;
        // Ensure disclaimer is present
        if (!reply.toLowerCase().includes('disclaimer') && !reply.toLowerCase().includes('consult a doctor')) {
          reply += '\n\n*Disclaimer: I am an AI health assistant. This information is for general educational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider.*';
        }
        return { reply, provider: 'gemini', modelUsed: aiResult.modelUsed };
      }
    } catch (error) {
      console.error('Gemini SDK Chat Error:', error.message);
      // Fall through to fallback
    }
  }

  // Fallback if API key missing or API call fails
  return null;
};

/**
 * Generate Structured AI Symptom Analysis
 */
const analyzeSymptomsWithAI = async (symptoms, language = 'en', dbDiseases = []) => {
  const apiKey = getApiKey();
  const symptomsText = Array.isArray(symptoms) ? symptoms.join(', ') : symptoms;

  if (apiKey) {
    try {
      let databaseContext = '';
      if (dbDiseases && dbDiseases.length > 0) {
        databaseContext = `\nDatabase Reference Conditions:\n` + dbDiseases.map(d => 
          `- ${d.name}: ${d.description}. Symptoms: ${d.symptoms ? d.symptoms.join(', ') : ''}. Urgency: ${d.urgency}`
        ).join('\n');
      }

      const prompt = `${SYSTEM_SYMPTOM_CHECKER_PROMPT}

Language: ${language}
User Symptoms Input: "${symptomsText}"
${databaseContext}`;

      const aiResult = await generateWithCandidateModels(prompt);
      if (aiResult && aiResult.text) {
        let cleanJson = aiResult.text;
        if (cleanJson.startsWith('```json')) {
          cleanJson = cleanJson.replace(/^```json\s*/, '').replace(/\s*```$/, '');
        } else if (cleanJson.startsWith('```')) {
          cleanJson = cleanJson.replace(/^```\s*/, '').replace(/\s*```$/, '');
        }

        const parsedData = JSON.parse(cleanJson);
        if (parsedData && Array.isArray(parsedData.results)) {
          return {
            results: parsedData.results,
            emergencyAlert: parsedData.emergencyAlert || false,
            emergencyMessage: parsedData.emergencyMessage || null,
            disclaimer: parsedData.disclaimer || "This symptom assessment is generated by AI for informational purposes only. Please consult a qualified doctor for clinical evaluation.",
            provider: 'gemini',
            modelUsed: aiResult.modelUsed
          };
        }
      }
    } catch (error) {
      console.error('Gemini SDK Symptom Analysis Error:', error.message);
      // Fall through to database fallback
    }
  }

  // Fallback: Construct structured result from MongoDB Disease matches
  if (dbDiseases && dbDiseases.length > 0) {
    const formattedResults = dbDiseases.map(disease => {
      const confirmedSymptomsList = Array.isArray(symptoms) ? symptoms : [symptoms];
      const matching = disease.symptoms ? disease.symptoms.filter(s => confirmedSymptomsList.some(userS => userS.toLowerCase().includes(s.toLowerCase()))) : [];
      const confidence = Math.min(95, Math.max(50, Math.round(((matching.length || 1) / (disease.symptoms?.length || 1)) * 100)));
      return {
        condition: disease.name,
        confidence,
        description: disease.description,
        symptoms: disease.symptoms || [],
        treatment: disease.treatment || ["Rest", "Hydration"],
        medication: disease.medication || ["Paracetamol if feverish"],
        diet: disease.diet || ["Balanced light meal"],
        urgency: disease.urgency || "consult-doctor",
        tests: disease.tests || []
      };
    }).sort((a, b) => b.confidence - a.confidence);

    return {
      results: formattedResults,
      emergencyAlert: formattedResults.some(r => r.urgency === 'emergency'),
      emergencyMessage: formattedResults.some(r => r.urgency === 'emergency') 
        ? "Warning: Your symptoms may indicate a high urgency condition. Please seek immediate emergency medical care."
        : null,
      disclaimer: "This symptom assessment is derived from database records for informational purposes. Please consult a doctor for diagnosis.",
      provider: 'database-fallback'
    };
  }

  return null;
};

module.exports = {
  generateChatResponse,
  analyzeSymptomsWithAI,
  CANDIDATE_MODELS
};
